'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var FLOATY_SET_LAYOUT = exports.FLOATY_SET_LAYOUT = 'FLOATY_SET_LAYOUT';
var FLOATY_START_FLOATING = exports.FLOATY_START_FLOATING = 'FLOATY_START_FLOATING';
var FLOATY_STOP_FLOATING = exports.FLOATY_STOP_FLOATING = 'FLOATY_STOP_FLOATING';
var FLOATY_ADD_ITEM = exports.FLOATY_ADD_ITEM = 'FLOATY_ADD_ITEM';

var FLOATY_TRANSFORM_INTO_COLUMN = exports.FLOATY_TRANSFORM_INTO_COLUMN = 'FLOATY_TRANSFORM_INTO_COLUMN';
var FLOATY_TRANSFORM_INTO_ROW = exports.FLOATY_TRANSFORM_INTO_ROW = 'FLOATY_TRANSFORM_INTO_ROW';

var FLOATY_REMOVE_TAB = exports.FLOATY_REMOVE_TAB = 'FLOATY_REMOVE_TAB';
var FLOATY_INSERT_TAB = exports.FLOATY_INSERT_TAB = 'FLOATY_INSERT_TAB';
var FLOATY_SET_ACTIVE_TAB = exports.FLOATY_SET_ACTIVE_TAB = 'FLOATY_SET_ACTIVE_TAB';
var FLOATY_REMOVE_ACTIVE_TAB = exports.FLOATY_REMOVE_ACTIVE_TAB = 'FLOATY_REMOVE_ACTIVE_TAB';
var FLOATY_ADD_TAB = exports.FLOATY_ADD_TAB = 'FLOATY_ADD_TAB';

var FLOATY_SET_GROW_VALUES = exports.FLOATY_SET_GROW_VALUES = 'FLOATY_SET_GROW_VALUES';