'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var UPDATE_GENERIC = exports.UPDATE_GENERIC = 'UPDATE_GENERIC';

var UPDATE_GROW_VALUES = exports.UPDATE_GROW_VALUES = 'UPDATE_GROW_VALUES';

var UPDATE_COLUMN = exports.UPDATE_COLUMN = 'UPDATE_COLUMN';
var UPDATE_COLUMN_ITEM = exports.UPDATE_COLUMN_ITEM = 'UPDATE_COLUMN_ITEM';
var TRANSFORM_INTO_COLUMN = exports.TRANSFORM_INTO_COLUMN = 'TRANSFORM_INTO_COLUMN';

var UPDATE_ROW = exports.UPDATE_ROW = 'UPDATE_ROW';
var UPDATE_ROW_ITEM = exports.UPDATE_ROW_ITEM = 'UPDATE_ROW_ITEM';
var TRANSFORM_INTO_ROW = exports.TRANSFORM_INTO_ROW = 'TRANSFORM_INTO_ROW';

var UPDATE_STACK = exports.UPDATE_STACK = 'UPDATE_STACK';
var UPDATE_STACK_ITEM = exports.UPDATE_STACK_ITEM = 'UPDATE_STACK_ITEM';
var UPDATE_ACTIVE_TAB = exports.UPDATE_ACTIVE_TAB = 'UPDATE_ACTIVE_TAB';
var REMOVE_TAB = exports.REMOVE_TAB = 'REMOVE_TAB';
var INSERT_TAB = exports.INSERT_TAB = 'INSERT_TAB';

var NO_OPERATION = exports.NO_OPERATION = 'NO_OPERATION';