export const FLOATY_UPDATE_GENERIC = 'FLOATY_UPDATE_GENERIC';
export const FLOATY_SET_LAYOUT = 'FLOATY_SET_LAYOUT';

export const FLOATY_UPDATE_GROW_VALUES = 'FLOATY_UPDATE_GROW_VALUES';

export const FLOATY_UPDATE_COLUMN = 'FLOATY_UPDATE_COLUMN';
export const FLOATY_UPDATE_COLUMN_ITEM = 'FLOATY_UPDATE_COLUMN_ITEM';
export const FLOATY_TRANSFORM_INTO_COLUMN = 'FLOATY_TRANSFORM_INTO_COLUMN';

export const FLOATY_UPDATE_ROW = 'FLOATY_UPDATE_ROW';
export const FLOATY_UPDATE_ROW_ITEM = 'FLOATY_UPDATE_ROW_ITEM';
export const FLOATY_TRANSFORM_INTO_ROW = 'FLOATY_TRANSFORM_INTO_ROW';

export const FLOATY_UPDATE_STACK = 'FLOATY_UPDATE_STACK';
export const FLOATY_UPDATE_STACK_ITEM = 'FLOATY_UPDATE_STACK_ITEM';
export const FLOATY_UPDATE_ACTIVE_TAB = 'FLOATY_UPDATE_ACTIVE_TAB';
export const FLOATY_REMOVE_TAB = 'FLOATY_REMOVE_TAB';
export const FLOATY_INSERT_TAB = 'FLOATY_INSERT_TAB';
export const FLOATY_REMOVE_ACTIVE_TAB = 'FLOATY_REMOVE_ACTIVE_TAB';
export const FLOATY_ADD_TAB = 'FLOATY_ADD_TAB';

export const FLOATY_NO_OPERATION = 'FLOATY_NO_OPERATION';
