export const FLOATY_SET_LAYOUT = 'FLOATY_SET_LAYOUT';
export const FLOATY_START_FLOATING = 'FLOATY_START_FLOATING';
export const FLOATY_STOP_FLOATING = 'FLOATY_STOP_FLOATING';
export const FLOATY_ADD_ITEM = 'FLOATY_ADD_ITEM';

export const FLOATY_TRANSFORM_INTO_COLUMN = 'FLOATY_TRANSFORM_INTO_COLUMN';
export const FLOATY_TRANSFORM_INTO_ROW = 'FLOATY_TRANSFORM_INTO_ROW';

export const FLOATY_REMOVE_TAB = 'FLOATY_REMOVE_TAB';
export const FLOATY_INSERT_TAB = 'FLOATY_INSERT_TAB';
export const FLOATY_SET_ACTIVE_TAB = 'FLOATY_SET_ACTIVE_TAB';
export const FLOATY_REMOVE_ACTIVE_TAB = 'FLOATY_REMOVE_ACTIVE_TAB';
export const FLOATY_ADD_TAB = 'FLOATY_ADD_TAB';

export const FLOATY_SET_GROW_VALUES = 'FLOATY_SET_GROW_VALUES';

export const FLOATY_SET_ITEM_STATE = 'FLOATY_SET_ITEM_STATE';
